spring.application.name=empleados-api

# Conexión a MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/empleados_db
spring.datasource.username=academia
spring.datasource.password=academia123

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# Swagger UI
springdoc.swagger-ui.path=/swagger-ui.htmlspring.data.web.pageable.max-page-size=50
